apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy98
  labels:
    app: autodeploy98
  namespace: namespace-workflow-1709027736251
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy98
  template:
    metadata:
      labels:
        app: autodeploy98
    spec:
      containers:
        - name: autodeploy98
          image: acrworkflow1709027736251.azurecr.io/image-workflow-1709027736251:latest
          ports:
            - containerPort: 5000