apiVersion: v1
kind: Service
metadata:
  name: autodeploy98
  namespace: namespace-workflow-1709027736251
spec:
  type: LoadBalancer
  selector:
    app: autodeploy98
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000